### ISSUE TITLE
language/script is not changing.....

### ISSUE THREAD

**Issue by iamQasim** [seanpue/ghalib.js#1]
i opened up a [page](http://www.columbia.edu/itc/mealac/pritchett/00ghalib/084/index_084.html) and want to read in urdu script but soon i clicked on it i got an error page saying only :

> Urdu, devanagari, and transliterated scripts are available on more advanced browsers -- more information
> after clicking on "more information" in above error page and got this:
> 
> More information
> You can view the Urdu text on these webpages in your choice of Urdu script, devanagari, transliteration, and plain roman.
> 
> The scripts used to generate the Urdu, devanagari, and transliteration texts on this site were recently update. Please file any issues here.(URL was http://www.columbia.edu/~asp49/00ghalib/moreinfo.html)

kindly correct it sooner possible... much blessings ... 

my info :
i encountered error on Chrome  50.0.2661.94 m and Safari ... both visited by indian :)

namaste
Qasim

**Comment by seanpue** [comment]
Fixed, thanks! You will have to clear your browser's cache for it to work.
